import logging
import re
from typing import Dict, Any, Optional, Tuple

from app.clients.tripletex import TripletexClient
from app.schemas import Plan

LOGGER = logging.getLogger(__name__)


def _extract_customer_fields(prompt: str) -> Tuple[str, Optional[str]]:
    prompt = prompt.strip()

    email_match = re.search(r"([A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,})", prompt)
    email = email_match.group(1) if email_match else None

    name_patterns = [
        r"som heter\s+(.+?)(?:\s+med e-?post|\s+med email|[.,]$)",
        r"named\s+(.+?)(?:\s+with e-?mail|\s+with email|[.,]$)",
        r"cliente\s+(.+?)(?:\s+con correo|\s+con e-?mail|[.,]$)",
    ]

    for pattern in name_patterns:
        match = re.search(pattern, prompt, re.IGNORECASE)
        if match:
            name = match.group(1).strip().strip(".").strip(",")
            return name, email

    fallback = re.search(r"kunde\s+(.+?)(?:[.,]$)", prompt, re.IGNORECASE)
    if fallback:
        return fallback.group(1).strip().strip(".").strip(","), email

    return "Customer generated by AI", email


def handle(client: TripletexClient, plan: Plan) -> Dict[str, Any]:
    details = plan.steps[0].details if plan.steps else {}
    prompt = details.get("prompt", "")

    customer_name, email = _extract_customer_fields(prompt)

    payload = {
        "name": customer_name,
        "isCustomer": True,
    }
    if email:
        payload["email"] = email

    LOGGER.info("Creating customer name=%s payload=%s", customer_name, payload)
    response = client.post("/customer", payload)
    LOGGER.info("Customer creation response status=%s body=%s", response.get("status", 200), response)

    return {
        "status": "created",
        "task": plan.task_type,
        "customer_name": customer_name,
        "email": email,
        "customer": response,
    }